// Generated by Haxe 3.4.2
(function () { "use strict";
var Remote = function(baseUrl) {
	this.baseUrl = baseUrl;
};
Remote.prototype = {
	get: function(url) {
		var _gthis = this;
		return new Promise(function(resolve,reject) {
			var request = new XMLHttpRequest();
			request.open("GET",_gthis.baseUrl + url,true);
			request.onload = function(e) {
				resolve(request.response);
				return;
			};
			request.onerror = function(e1) {
				console.log("An error occured...");
				console.log(e1);
				reject("");
			};
			request.send();
		});
	}
};
var Gallery = function() { };
Gallery.main = function() {
	var Api = new Remote("http://localhost/gallery");
	Api.get("/list.json").then(function(jsonGallery) {
		var gallery = JSON.parse(jsonGallery);
		Gallery.appendImages(gallery.imgs);
	});
};
Gallery.appendImages = function(urls) {
	var _g = 0;
	while(_g < urls.length) {
		var url = urls[_g];
		++_g;
		var imageNode = window.document.createElement("img");
		imageNode.setAttribute("src","http://localhost/gallery/" + url);
		imageNode.setAttribute("width","250px");
		imageNode.setAttribute("style","display: block; border: 3px solid #ddd; margin: 20px auto 20px auto;");
		window.document.getElementById("gallery").appendChild(imageNode);
	}
};
Gallery.main();
})();
